# Generated by Django 4.2.9 on 2026-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('term', models.CharField(max_length=255)),
                ('at', models.DateTimeField()),
            ],
            options={
                'db_table': 'recent_searches',
            },
        ),
    ]
