# Generated by Django 4.2.9 on 2026-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
