# Generated by Django 4.2.9 on 2026-04-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_create_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
