# Generated by Django 4.2.9 on 2026-03-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('para', 'Paragraph'), ('list', 'List'), ('figure', 'Figure'), ('table', 'Table')], max_length=20)),
                ('order', models.IntegerField(help_text='Document order within parent node')),
                ('content_html', models.TextField(blank=True, default='', help_text='Pre-rendered HTML content for this block')),
                ('raw_data', models.JSONField(blank=True, help_text='Structured data: table CALS structure, list items, figure metadata', null=True)),
            ],
            options={
                'db_table': 'content_block',
                'ordering': ['node', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('section', 'Section'), ('leaf_group', 'Leaf Group'), ('leaf', 'Leaf')], max_length=20)),
                ('xml_id', models.CharField(db_index=True, help_text="Original ID from XML, e.g. 'CALM_DS_sec_1_2_3'", max_length=200)),
                ('number', models.CharField(help_text="Dotted section number, e.g. '1.2.3'", max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('level', models.IntegerField(default=1, help_text='Heading level (1-6) for sections')),
                ('path', models.CharField(db_index=True, help_text="Materialized path for fast traversal, e.g. '1.2.3'", max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Sort order among siblings')),
            ],
            options={
                'db_table': 'content_node',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(default='Technical Manual', max_length=100)),
                ('classification', models.CharField(default='UNCLASSIFIED', max_length=50)),
                ('generated_date', models.DateField(blank=True, null=True)),
                ('generator_version', models.CharField(default='1.0', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_document',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('3d_model', '3D Model'), ('video', 'Video'), ('pdf', 'PDF')], max_length=20)),
                ('file_path', models.CharField(help_text='Relative path to media file from MEDIA_ROOT', max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('xml_id', models.CharField(blank=True, db_index=True, default='', help_text="Original ID from XML, e.g. 'fig-1.1' or 'tbl-2.3'", max_length=200)),
                ('number', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, default='', help_text='Image format: png, jpeg, gif, webp', max_length=20)),
                ('block', models.ForeignKey(blank=True, help_text='Content block this media belongs to (figure/table)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.contentblock')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.document')),
            ],
            options={
                'db_table': 'content_media',
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('target_xml_id', models.CharField(blank=True, default='', help_text='Raw target ID from XML for fallback resolution', max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='content.media')),
                ('target_node', models.ForeignKey(blank=True, help_text='Target section/leaf this hotspot navigates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_targets', to='content.contentnode')),
            ],
            options={
                'db_table': 'content_hotspot',
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('figure', 'Figure'), ('table', 'Table'), ('section', 'Section')], max_length=20)),
                ('display_text', models.CharField(help_text="Display text, e.g. 'Figure 1.1'", max_length=200)),
                ('target_xml_id', models.CharField(db_index=True, help_text="Target ID from XML, e.g. 'fig-1.1'", max_length=200)),
                ('source_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrefs', to='content.contentblock')),
                ('target_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_xrefs', to='content.media')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_xrefs', to='content.contentnode')),
            ],
            options={
                'db_table': 'content_crossreference',
            },
        ),
        migrations.AddField(
            model_name='contentnode',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='content.document'),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='leaf_group_root',
            field=models.ForeignKey(blank=True, help_text='For leaf-group nodes: FK to the root section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_group_members', to='content.contentnode'),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.contentnode'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.contentnode'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['document', 'xml_id'], name='content_med_documen_a2db57_idx'),
        ),
        migrations.AddIndex(
            model_name='crossreference',
            index=models.Index(fields=['target_xml_id'], name='content_cro_target__28676b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['document', 'path'], name='content_nod_documen_447a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['document', 'xml_id'], name='content_nod_documen_cbf067_idx'),
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['parent', 'order'], name='content_nod_parent__56063d_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentnode',
            constraint=models.UniqueConstraint(fields=('document', 'xml_id'), name='unique_node_per_doc'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['node', 'order'], name='content_blo_node_id_3cf90e_idx'),
        ),
    ]
