# Generated by Django 4.2.9 on 2026-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_meshhotspot_media_block_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'image_hotspots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'models_3d',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_name', models.CharField(max_length=255)),
                ('target_topic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'model_hotspots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('topic_title', models.TextField(null=True)),
                ('printed_at', models.TextField(null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'db_table': 'printlogs',
                'managed': False,
            },
        ),
    ]
