# Generated by Django 4.2.9 on 2026-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('topic_title', models.CharField(max_length=255)),
                ('topic_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
    ]
