# Generated by Django 4.2.9 on 2026-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
